#!/bin/env bash
# Created by Carletti Stefano
# date: dom 20 set 2026, 23:15:20, CEST
# MIT License

info() {
	echo "[info] $1"
}
debug() {
	echo "[debug] $1"
}
error() {
	echo "[error] $1" >&2
}
fatal() {
	echo "[fatal] $1" >&2
	if [[ $2 -ne 0 ]]; then
		exit "$2"
	else
		exit 1
	fi
}

DEFAULT_DATABASE="$HOME/.config/password_manager/passwords.db"

main() {
	# check if sqlite is installed
	sqlite3 --help &> /dev/null || fatal "'sqlite3' package is required but was not detected!" 2

	# show interface
	clear
	echo "Password manager"

	return 0
}

main "$@"

